DROP TABLE IF EXISTS crashes_raw;

CREATE TABLE crashes_raw (
    crash_date                        date,
    crash_time                        time,
    borough                           text,
    zip_code                          text,
    latitude                          numeric,
    longitude                         numeric,
    location                          text,
    on_street_name                    text,
    off_street_name                   text,
    cross_street_name                 text,
    number_of_persons_injured         numeric,
    number_of_persons_killed          numeric,
    number_of_pedestrians_injured     numeric,
    number_of_pedestrians_killed      numeric,
    number_of_cyclist_injured         numeric,
    number_of_cyclist_killed          numeric,
    number_of_motorist_injured        numeric,
    number_of_motorist_killed         numeric,
    contributing_factor_vehicle_1     text,
    contributing_factor_vehicle_2     text,
    contributing_factor_vehicle_3     text,
    contributing_factor_vehicle_4     text,
    contributing_factor_vehicle_5     text,
    collision_id                      bigint,
    vehicle_type_code1                text,
    vehicle_type_code2                text,
    vehicle_type_code_3               text,
    vehicle_type_code_4               text,
    vehicle_type_code_5               text
);
